### ISSUE TITLE
Can not delete duplicate socket 

### ISSUE THREAD

**Issue by ceremcem** [ceremcem/fc-asm3-cut-window#1]
In [this model](https://github.com/ceremcem/fc-asm3-cut-window/tree/415ac978d19e422954262936faf50c7aa5e6f8be) I'm not able to delete the duplicate socket because it also removes the original one: 

![image](https://user-images.githubusercontent.com/6639874/44006932-1df4e026-9e95-11e8-9efd-6604ea5b8613.png)

**Comment by realthunder** [comment]
How did you reveal the duplicate? Can you repeat the process? Did you manually change the 'Visibility' property of some 'Body'?

These two instance may in fact be the same object within two coordinate system. One is the in the assembly coordinate system, this other is in the global one. The 'Visibility' property of an object control its visibility in the global coordinate system. When you add an object inside assembly coordinate system, the object will appear in another coordinate system, and hide itself in the global coordinate system. By right, if you don't mess with the 'Visibility' property, this shouldn't happen.

**Comment by ceremcem** [comment]
It is happened as I was trying to create a sketch right on the face of `connector`. AFAIR, I moved the `connector` out of `enclosure`, tried to draw a sketch on it. After a few trials, I gave up and moved the `connector` back into the `device`, but there were two `connector`s. 

I tried to reproduce the same, but it doesn't happen at the moment.

**Comment by realthunder** [comment]
The Sketch editor has a feature to manage the dependent's visibility automatically, you probably triggered some bug.

**Comment by realthunder** [comment]
Next time this happen again, you can tell which is which by move your mouse over the object and observe the status bar message. If it shows *doc_name.obj_name.face_name* Then this is the one in the global coordinate system. Simply hit the space key to hide it. The other one should be *doc_name.container_name.more_container.obj_name.face_name*

**Comment by ceremcem** [comment]
Okay. Thanks. I'm sure I'll hit it again.

**Comment by ceremcem** [comment]
I'm going to close this issue because I  can not reproduce it again.
